--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pjz9n-pm-pl/MorseChat
build-by-default: true
branches:
  - main
projects:
  MorseChat:
    libs:
      - src: pjz9n/resourcepacktools/ResourcePackTools
        version: 2.0.0
...
